/* Invoked by scripts/ideas_dom_check.py; fixtures never depend on an empty real feed. */
const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const script = fs.readFileSync(path.join(root, 'ideas/assets/app.js'), 'utf8');
const fixture = JSON.parse(fs.readFileSync(path.join(root, 'ideas/demo/data/index.json')));
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function open(route, options = {}) {
  const address = new URL(route, 'https://jiadlu.github.io');
  const file = path.join(root, address.pathname, 'index.html');
  const dom = new JSDOM(fs.readFileSync(file, 'utf8'), {url: address.href, runScripts: 'outside-only', pretendToBeVisual: true});
  const w = dom.window, d = w.document;
  const copied = [];
  Object.defineProperty(w.navigator, 'clipboard', {value: {writeText: async value => {
    if (options.clipboardFail) throw new Error('Unavailable');
    copied.push(value);
  }}});
  w.Element.prototype.scrollIntoView = function () {};
  w.fetch = async () => ({ok: !options.fail, json: async () => structuredClone(options.data || fixture)});
  w.eval(script); await delay(20);
  return {w, d, copied, close: () => w.close()};
}
function change(a, name, value) {
  const element = a.d.querySelector('#filters').elements.namedItem(name);
  element.value = value;
  element.dispatchEvent(new a.w.Event(name === 'q' ? 'input' : 'change', {bubbles: true}));
}
(async () => {
  let a = await open('/ideas/');
  assert.ok(a.d.querySelector('.feed-toolbar'));
  assert.equal(a.d.querySelector('.demo-banner'), null);
  a.close();
  a = await open('/ideas/demo/');
  assert.equal(a.d.querySelectorAll('.entry').length, fixture.posts.length);
  assert.ok(a.d.querySelector('.demo-banner'));
  assert.match(a.d.querySelector('.entry.idea .entry-text').textContent, /魔法/);
  a.close();
  a = await open('/ideas/demo/archive/?kind=idea&tag=agents&from=2026-09-19');
  assert.equal(a.d.querySelectorAll('.entry').length, 1);
  assert.match(a.d.querySelector('#result-count').textContent, /1 条/);
  change(a, 'to', '2026-09-01');
  assert.equal(a.d.querySelector('#filter-error').hidden, false);
  assert.equal(a.d.querySelectorAll('.entry').length, 0);
  a.d.querySelector('button[type="reset"]').click(); await delay(10);
  assert.equal(a.d.querySelectorAll('.entry').length, 4);
  change(a, 'q', 'silent_failures'); await delay(180);
  assert.equal(a.d.querySelectorAll('.entry').length, 1);
  assert.match(a.d.querySelector('.entry').textContent, /漂亮的 Agent/);
  assert.match(a.w.location.search, /q=silent_failures/);
  change(a, 'q', '<img src=x onerror=alert(1)>'); await delay(180);
  assert.equal(a.d.querySelector('#archive-results img'), null);
  assert.match(a.d.querySelector('#archive-results').textContent, /没有记录/);
  a.w.history.pushState({}, '', '?kind=note&month=2026-09');
  a.w.dispatchEvent(new a.w.PopStateEvent('popstate'));
  assert.equal(a.d.querySelectorAll('.entry').length, 1);
  assert.match(a.d.querySelector('.entry').textContent, /脑子/);
  a.close();
  const many = structuredClone(fixture);
  many.posts = Array.from({length: 31}, (_, i) => ({...fixture.posts[0], id: `fixture-${i}`}));
  a = await open('/ideas/demo/archive/', {data: many});
  assert.equal(a.d.querySelectorAll('.entry').length, 12);
  a.d.querySelector('[data-page="2"]').click();
  assert.equal(a.d.querySelectorAll('.entry').length, 12);
  assert.match(a.w.location.search, /page=2/);
  a.d.querySelector('[data-page="3"]').click();
  assert.equal(a.d.querySelectorAll('.entry').length, 7);
  assert.ok(a.d.querySelector('[data-page="4"]').disabled);
  a.close();
  a = await open('/ideas/archive/', {data: {version: 1, demo: false, posts: []}});
  assert.match(a.d.querySelector('#archive-results').textContent, /还没有发布/);
  a.close();
  a = await open('/ideas/demo/archive/', {fail: true});
  assert.equal(a.d.querySelectorAll('.entry').length, 4);
  assert.equal(a.d.querySelector('#filter-error').hidden, false);
  assert.ok(a.d.querySelector('[name="q"]').disabled);
  a.close();
  a = await open('/ideas/demo/posts/demo-after-the-demo/');
  assert.equal(a.d.querySelectorAll('.toc a').length, 3);
  a.d.querySelectorAll('.toc a').forEach(link => assert.ok(a.d.querySelector(link.getAttribute('href'))));
  a.d.querySelector('.copy-code').click(); await delay(5);
  assert.match(a.copied[0], /silent_failures/);
  a.d.querySelector('.copy-link').click(); await delay(5);
  assert.equal(a.copied[1], 'https://jiadlu.github.io/ideas/demo/posts/demo-after-the-demo/');
  assert.ok(a.d.querySelector('#source-engineering'));
  a.close();
  a = await open('/ideas/demo/posts/demo-boring-is-good/', {clipboardFail: true});
  assert.equal(a.d.querySelector('.toc'), null);
  a.d.querySelector('.copy-link').click(); await delay(5);
  assert.match(a.d.querySelector('.announcement').textContent, /手动复制/);
  a.close();
  console.log('Ideas DOM checks passed: feed, short/long reading, combined filters, dates, full-text search, history, pagination, source anchors, clipboard and fallback.');
})().catch(error => {console.error(error); process.exitCode = 1;});
